---
- name: Install dependencies
  become: True
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - base-devel
    - git

- name: Clone yay from github
  become: True
  become_user: root
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: /tmp/yay
    version: master
    update: True
  tags:
    - yay

- name: Run makepkg --noconfirm -si
  ansible.builtin.command: makepkg --noconfirm -si
  become: True
  become_user: root
  args:
    chdir: /tmp/yay
    creates: /usr/bin/yay
  tags:
    - yay
